CREATE TABLE IF NOT EXISTS BOOK
(
   `ID` VARCHAR (300) NOT NULL,
   `TITLE` VARCHAR (300) NOT NULL,
  `PUBLISHDATE` DATETIME NOT NULL,
   `AUTHOR` VARCHAR (300) NOT NULL,
   `TYPE` VARCHAR (300) NOT NULL,
   `PRICE` DOUBLE NOT NULL,
  `NUMOFPAGES` INTEGER NOT NULL,
   `PUBLISHER` VARCHAR (300) NOT NULL UNIQUE,
   `LANGUAGE` VARCHAR (300) NOT NULL,
   `ISBN13` VARCHAR (20) NULL,
   PRIMARY KEY (ID)
);