CREATE TABLE IF NOT EXISTS ORDER_DETAILS
(
`ID` BIGINT NOT NULL AUTO_INCREMENT UNIQUE,
`BOOK_ID` VARCHAR (300) NOT NULL,
`ISBN` VARCHAR (300) NOT NULL,
`PUBLISH_DATE` DATE NOT NULL,
`QUANITY`INTEGER NOT NULL,
  
   PRIMARY KEY (BOOK_ID)
);